# Generated by Django 4.2.11 on 2024-09-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='phon_number',
            new_name='phone_number',
        ),
    ]
